version: '3.9'

services:
  php:
    container_name: project_app
    ports:
      - ${WEB_PORT}:80
    build: 
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./src:/var/www/html
      - ./docker/apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - db
  
  db:
    container_name: project_db
    image: mysql:8.0
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
  
  db-test:
    container_name: project_db_test
    image: mysql:8.0
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - ${DB_TEST_PORT}:3306
    environment:
      MYSQL_HOST: db-test
      MYSQL_DATABASE: ${DB_TEST_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/db-test/data:/var/lib/mysql
      - ./docker/db-test/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db-test/sql:/docker-entrypoint-initdb.d
  
  phpmyadmin:
    container_name: project_pma
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - ${PMA_PORT}:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/pma/phpmyadmin/sessions:/sessions